
EMDerivation.pdf: EMDerivation.tex
	pdflatex -output-fromat=pdf EMDerivation.tex

model0.pdf: model0.tex
	pdflatex -output-fromat=pdf model0.tex

model1GibbsDerivation.pdf: model1GibbsDerivation.tex
	pdflatex -output-fromat=pdf model1GibbsDerivation.tex 
